/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 ./public/gltf/flowy-tree.glb --shadows --output ./app/components/gltf/FlowyTree.tsx --types --root ./public/ --debug
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008: THREE.Mesh
    Plane009: THREE.Mesh
    Plane010: THREE.Mesh
    Plane011: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane015: THREE.Mesh
    Plane016: THREE.Mesh
    Plane017: THREE.Mesh
    Plane018: THREE.Mesh
    Plane019: THREE.Mesh
    Plane020: THREE.Mesh
    Plane021: THREE.Mesh
    Plane022: THREE.Mesh
    Plane023: THREE.Mesh
    Plane024: THREE.Mesh
    Plane025: THREE.Mesh
    Plane026: THREE.Mesh
    Plane027: THREE.Mesh
    Plane028: THREE.Mesh
    Plane029: THREE.Mesh
    Plane030: THREE.Mesh
    Plane031: THREE.Mesh
    Plane032: THREE.Mesh
    Plane033: THREE.Mesh
    Plane034: THREE.Mesh
    Plane035: THREE.Mesh
    Plane036: THREE.Mesh
    Plane037: THREE.Mesh
    Plane038: THREE.Mesh
    Plane039: THREE.Mesh
    Plane040: THREE.Mesh
    Plane041: THREE.Mesh
    Plane042: THREE.Mesh
    Plane043: THREE.Mesh
    Plane044: THREE.Mesh
    Plane045: THREE.Mesh
    Plane046: THREE.Mesh
    Plane047: THREE.Mesh
    Plane048: THREE.Mesh
    Plane049: THREE.Mesh
    Plane050: THREE.Mesh
    Plane051: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gltf/flowy-tree.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0.028, 4.251, 0]} scale={[0.373, 4.206, 0.373]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[0.037, 1.638, 0.213]} scale={[1.693, 1, 0.283]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[0.037, 1.638, 0.213]} rotation={[-2.874, 0.903, 2.782]} scale={[1.876, 1.108, 0.314]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials['Material.002']} position={[0.037, 1.638, 0.213]} rotation={[-2.801, -0.575, 3.102]} scale={[1.618, 0.389, 0.267]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials['Material.002']} position={[0.037, 1.638, 0.213]} rotation={[0.842, -1.32, 0.676]} scale={[1.921, 0.958, 0.271]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane004.geometry} material={materials['Material.002']} position={[0.101, 2.286, 0.007]} rotation={[0, 1.307, 0]} scale={[1.625, 0.959, 0.272]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane005.geometry} material={materials['Material.002']} position={[0.101, 2.286, 0.007]} rotation={[-2.964, -0.382, 3.061]} scale={[1.8, 1.063, 0.301]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane006.geometry} material={materials['Material.002']} position={[0.101, 2.286, 0.007]} rotation={[-0.72, -1.132, -0.901]} scale={[1.553, 0.373, 0.256]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007.geometry} material={materials['Material.002']} position={[0.101, 2.286, 0.007]} rotation={[0.187, -0.093, -0.132]} scale={[1.843, 0.92, 0.26]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane008.geometry} material={materials['Material.002']} position={[0.01, 3.237, 0.234]} rotation={[0, -0.655, 0]} scale={[1.681, 0.993, 0.281]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane009.geometry} material={materials['Material.002']} position={[0.01, 3.237, 0.234]} rotation={[-1.546, 1.406, 1.398]} scale={[1.863, 1.1, 0.312]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane010.geometry} material={materials['Material.002']} position={[0.01, 3.237, 0.234]} rotation={[-2.857, 0.05, 2.897]} scale={[1.607, 0.386, 0.265]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane011.geometry} material={materials['Material.002']} position={[0.01, 3.237, 0.234]} rotation={[2.758, -1.053, 2.655]} scale={[1.908, 0.952, 0.269]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane012.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[0, -1.219, 0]} scale={[1.555, 0.918, 0.26]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane013.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[-0.299, 0.982, 0.103]} scale={[1.722, 1.017, 0.288]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane014.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[-2.798, 0.588, 2.715]} scale={[1.486, 0.357, 0.245]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane015.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[2.928, -0.511, 2.886]} scale={[1.764, 0.88, 0.249]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane016.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[-2.957, -0.698, Math.PI]} scale={[1.555, 0.918, 0.26]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane017.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[0.016, -0.219, -0.184]} scale={[1.722, 1.017, 0.288]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane018.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[-0.646, 1.181, 0.561]} scale={[1.486, 0.357, 0.245]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane019.geometry} material={materials['Material.002']} position={[0.381, 4.375, -0.068]} rotation={[3.084, 0.69, -3.135]} scale={[1.764, 0.88, 0.249]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane020.geometry} material={materials['Material.002']} position={[0.505, 5.213, -0.038]} rotation={[-2.992, 0.342, 2.972]} scale={[1.357, 0.801, 0.227]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane021.geometry} material={materials['Material.002']} position={[0.505, 5.213, -0.038]} rotation={[0.053, -1.27, -0.138]} scale={[1.504, 0.888, 0.252]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane022.geometry} material={materials['Material.002']} position={[0.505, 5.213, -0.038]} rotation={[-0.235, 0.197, -0.001]} scale={[1.297, 0.312, 0.214]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane023.geometry} material={materials['Material.002']} position={[0.505, 5.213, -0.038]} rotation={[0.257, 1.394, -0.283]} scale={[1.54, 0.768, 0.217]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane024.geometry} material={materials['Material.002']} position={[0.65, 5.978, -0.306]} rotation={[-2.741, 1.202, 2.646]} scale={[1.148, 0.678, 0.192]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane025.geometry} material={materials['Material.002']} position={[0.65, 5.978, -0.306]} rotation={[3.113, -0.987, 2.93]} scale={[1.272, 0.751, 0.213]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane026.geometry} material={materials['Material.002']} position={[0.65, 5.978, -0.306]} rotation={[-0.293, -0.66, -0.231]} scale={[1.098, 0.264, 0.181]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane027.geometry} material={materials['Material.002']} position={[0.65, 5.978, -0.306]} rotation={[0.051, 0.516, -0.056]} scale={[1.303, 0.65, 0.184]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane028.geometry} material={materials['Material.002']} position={[0.566, 6.541, -0.177]} rotation={[-0.119, 0.133, -0.292]} scale={[1.024, 0.605, 0.171]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane029.geometry} material={materials['Material.002']} position={[0.566, 6.541, -0.177]} rotation={[2.924, 0.793, -3.043]} scale={[1.134, 0.67, 0.19]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane030.geometry} material={materials['Material.002']} position={[0.566, 6.541, -0.177]} rotation={[-2.731, -0.572, -2.8]} scale={[0.978, 0.235, 0.161]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane031.geometry} material={materials['Material.002']} position={[0.566, 6.541, -0.177]} rotation={[-0.452, -1.255, -0.516]} scale={[1.161, 0.579, 0.164]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane032.geometry} material={materials['Material.002']} position={[0.338, 6.985, -0.144]} rotation={[-3.018, -1.039, 2.908]} scale={[0.754, 0.445, 0.126]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane033.geometry} material={materials['Material.002']} position={[0.338, 6.985, -0.144]} rotation={[0.146, 0.109, -0.009]} scale={[0.835, 0.493, 0.14]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane034.geometry} material={materials['Material.002']} position={[0.338, 6.985, -0.144]} rotation={[-1.446, 1.161, 1.549]} scale={[0.721, 0.173, 0.119]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane035.geometry} material={materials['Material.002']} position={[0.338, 6.985, -0.144]} rotation={[-2.971, 0.365, 2.936]} scale={[0.856, 0.427, 0.121]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane036.geometry} material={materials['Material.002']} position={[0.304, 7.398, -0.123]} rotation={[-0.078, 0.83, 0.13]} scale={[0.651, 0.384, 0.109]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane037.geometry} material={materials['Material.002']} position={[0.304, 7.398, -0.123]} rotation={[-2.952, 0.07, 2.893]} scale={[0.721, 0.426, 0.121]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane038.geometry} material={materials['Material.002']} position={[0.304, 7.398, -0.123]} rotation={[-2.132, -1.335, -2.406]} scale={[0.622, 0.15, 0.102]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane039.geometry} material={materials['Material.002']} position={[0.304, 7.398, -0.123]} rotation={[0.29, -0.535, 0.068]} scale={[0.739, 0.368, 0.104]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane040.geometry} material={materials['Material.002']} position={[0.203, 7.62, -0.104]} rotation={[-2.724, 0.377, 2.681]} scale={[0.587, 0.346, 0.098]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane041.geometry} material={materials['Material.002']} position={[0.203, 7.62, -0.104]} rotation={[1.061, -1.226, 0.746]} scale={[0.65, 0.384, 0.109]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane042.geometry} material={materials['Material.002']} position={[0.203, 7.62, -0.104]} rotation={[-0.099, 0.046, 0.231]} scale={[0.561, 0.135, 0.092]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane043.geometry} material={materials['Material.002']} position={[0.203, 7.62, -0.104]} rotation={[-0.517, 1.235, 0.68]} scale={[0.666, 0.332, 0.094]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane044.geometry} material={materials['Material.002']} position={[0.16, 7.927, -0.038]} rotation={[-2.277, 1.242, 2.175]} scale={[0.587, 0.346, 0.098]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane045.geometry} material={materials['Material.002']} position={[0.16, 7.927, -0.038]} rotation={[3.007, -0.853, 2.773]} scale={[0.65, 0.384, 0.109]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane046.geometry} material={materials['Material.002']} position={[0.16, 7.927, -0.038]} rotation={[-0.209, -0.808, -0.135]} scale={[0.561, 0.135, 0.092]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane047.geometry} material={materials['Material.002']} position={[0.16, 7.927, -0.038]} rotation={[0.017, 0.393, 0.067]} scale={[0.666, 0.332, 0.094]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane048.geometry} material={materials['Material.002']} position={[0.11, 8.238, -0.029]} rotation={[-2.868, -0.432, 3.129]} scale={[0.559, 0.33, 0.094]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane049.geometry} material={materials['Material.002']} position={[0.11, 8.238, -0.029]} rotation={[0.1, -0.483, -0.221]} scale={[0.62, 0.366, 0.104]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane050.geometry} material={materials['Material.002']} position={[0.11, 8.238, -0.029]} rotation={[-0.255, 0.965, 0.228]} scale={[0.535, 0.129, 0.088]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane051.geometry} material={materials['Material.002']} position={[0.11, 8.238, -0.029]} rotation={[3.115, 0.948, -3.046]} scale={[0.635, 0.317, 0.09]} />
    </group>
  )
}

useGLTF.preload('/gltf/flowy-tree.glb')
