/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 ./public/gltf/island.glb --shadows --output ./app/components/gltf/Island.tsx --types --root ./public/ --debug
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Icosphere002_1: THREE.Mesh
    Icosphere002_2: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere008: THREE.Mesh
    Plane002: THREE.Mesh
    Icosphere009: THREE.Mesh
    Icosphere010: THREE.Mesh
    Icosphere011: THREE.Mesh
    Icosphere012: THREE.Mesh
    Icosphere013: THREE.Mesh
    Icosphere014: THREE.Mesh
    Plane003: THREE.Mesh
    Icosphere015: THREE.Mesh
    Icosphere016: THREE.Mesh
    Icosphere017: THREE.Mesh
    Icosphere018: THREE.Mesh
    Icosphere019: THREE.Mesh
    Icosphere020: THREE.Mesh
    Plane004: THREE.Mesh
    Icosphere021: THREE.Mesh
    Icosphere022: THREE.Mesh
    Icosphere023: THREE.Mesh
    Icosphere024: THREE.Mesh
    Icosphere025: THREE.Mesh
    Icosphere026: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gltf/island.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[0.429, 2.134, 0.051]} rotation={[0.187, 0, 0]} scale={15} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={materials['Material.003']} position={[7.854, 5.62, -1.709]} rotation={[0.523, 0.487, 0.769]} scale={0.641} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere003.geometry} material={materials['Material.005']} position={[8.305, 5.452, -0.784]} rotation={[-0.005, 0.637, 1.26]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere004.geometry} material={materials['Material.006']} position={[7.327, 5.114, -1.303]} rotation={[-0.017, 0.341, 0.456]} scale={0.475} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere002.geometry} material={materials['Material.004']} position={[9.256, 5.053, -1.732]} rotation={[0.023, 0.525, 0.942]} scale={0.624} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere005.geometry} material={materials['Material.003']} position={[1.79, 3.407, 3.079]} rotation={[2.438, -0.82, -2.664]} scale={0.45} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere006.geometry} material={materials['Material.005']} position={[1.244, 3.289, 2.606]} rotation={[-3.134, -1.041, -1.878]} scale={0.365} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere007.geometry} material={materials['Material.006']} position={[2.019, 3.051, 2.672]} rotation={[-3.12, -0.744, -2.676]} scale={0.333} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere008.geometry} material={materials['Material.004']} position={[0.891, 3.008, 3.481]} rotation={[3.108, -0.929, -2.215]} scale={0.438} />
      <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials['Material.008']} position={[-2.138, 0.928, 6.701]} scale={[0.403, 0.344, 0.403]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere009.geometry} material={materials['Material.009']} position={[-5.387, 1.1, 7.973]} scale={[0.975, 0.773, 0.975]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere010.geometry} material={materials['Material.009']} position={[-3.341, 1.766, 9.551]} rotation={[-0.028, 0.783, 0.035]} scale={[0.874, 0.693, 0.874]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere011.geometry} material={materials['Material.009']} position={[-5.111, 2.573, 6.027]} rotation={[-0.01, -0.633, -0.01]} scale={[0.829, 0.657, 0.829]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere012.geometry} material={materials['Material.009']} position={[-1.131, 3.457, 4.632]} rotation={[-3.065, -0.715, -3.11]} scale={[0.655, 0.519, 0.655]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere013.geometry} material={materials['Material.009']} position={[-0.418, 4.137, 6.19]} rotation={[-3.083, 0.097, 3.117]} scale={[0.488, 0.387, 0.488]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere014.geometry} material={materials['Material.009']} position={[-1.299, 4.802, 5.256]} rotation={[-3.069, -0.653, -3.116]} scale={[0.458, 0.363, 0.458]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials['Material.008']} position={[-1.328, 4.277, -1.364]} scale={[0.19, 0.199, 0.19]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere015.geometry} material={materials['Material.009']} position={[-2.863, 4.377, -0.764]} scale={[0.46, 0.447, 0.46]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere016.geometry} material={materials['Material.009']} position={[-1.896, 4.762, -0.018]} rotation={[-0.028, 0.783, 0.035]} scale={[0.413, 0.401, 0.413]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere017.geometry} material={materials['Material.009']} position={[-2.732, 5.228, -1.682]} rotation={[-0.01, -0.633, -0.01]} scale={[0.391, 0.38, 0.391]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere018.geometry} material={materials['Material.009']} position={[-0.853, 5.739, -2.341]} rotation={[-3.065, -0.715, -3.11]} scale={[0.309, 0.3, 0.31]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere019.geometry} material={materials['Material.009']} position={[-0.516, 6.132, -1.605]} rotation={[-3.083, 0.097, 3.117]} scale={[0.23, 0.223, 0.231]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere020.geometry} material={materials['Material.009']} position={[-0.932, 6.516, -2.047]} rotation={[-3.069, -0.653, -3.116]} scale={[0.216, 0.21, 0.216]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane004.geometry} material={materials['Material.008']} position={[-0.038, 3.693, -1.375]} scale={[0.217, 0.23, 0.217]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere021.geometry} material={materials['Material.009']} position={[-1.835, 3.898, -0.718]} scale={[0.525, 0.516, 0.525]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere022.geometry} material={materials['Material.009']} position={[-0.733, 4.343, 0.132]} rotation={[-0.028, 0.783, 0.035]} scale={[0.471, 0.463, 0.471]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere023.geometry} material={materials['Material.009']} position={[-1.686, 4.881, -1.766]} rotation={[-0.01, -0.633, -0.01]} scale={[0.446, 0.439, 0.446]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere024.geometry} material={materials['Material.009']} position={[0.458, 5.471, -2.518]} rotation={[-3.065, -0.715, -3.11]} scale={[0.353, 0.346, 0.353]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere025.geometry} material={materials['Material.009']} position={[0.842, 5.925, -1.678]} rotation={[-3.083, 0.097, 3.117]} scale={[0.263, 0.258, 0.263]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere026.geometry} material={materials['Material.009']} position={[0.424, 6.299, -2.143]} rotation={[-3.069, -0.653, -3.116]} scale={[0.247, 0.242, 0.247]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere002_1.geometry} material={materials.Material} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere002_2.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/gltf/island.glb')
