/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/gltf/hubs.glb --shadows --output ./app/components/gltf/Hubs.tsx --types --root ./public/ --debug
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_26: THREE.Mesh
    navMesh: THREE.Mesh
    Cudillero_Bake_Final001: THREE.Mesh
    CombinedMesh: THREE.Mesh
    CombinedMesh_1: THREE.Mesh
  }
  materials: {
    ['05___Default']: THREE.MeshBasicMaterial
    BigShadow: THREE.MeshBasicMaterial
    Floweshop_Details: THREE.MeshBasicMaterial
    Foam: THREE.MeshBasicMaterial
    material: THREE.MeshBasicMaterial
    Material__58: THREE.MeshBasicMaterial
    Painting: THREE.MeshBasicMaterial
    Shrub: THREE.MeshBasicMaterial
    Wiring: THREE.MeshBasicMaterial
    ['16___Default']: THREE.MeshBasicMaterial
    Manhole: THREE.MeshBasicMaterial
    Material__57: THREE.MeshBasicMaterial
    Water: THREE.MeshBasicMaterial
    Cudillero_BakeObject022_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject023_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject024_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject025_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject026_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject027_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject028_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject029_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject030_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject032_mtl: THREE.MeshBasicMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Cudillero_BakeObject031_mtl: THREE.MeshBasicMaterial
    Cudillero_BakeObject033_mtl: THREE.MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gltf/village.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.201, 15]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.023}>
          <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials['05___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.BigShadow} />
          <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Floweshop_Details} />
          <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Foam} />
          <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.Material__58} />
          <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.Painting} />
          <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.Shrub} />
          <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Wiring} />
          <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials['16___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Manhole} />
          <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.Material__57} />
          <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.Water} />
          <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.Cudillero_BakeObject022_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.Cudillero_BakeObject023_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.Cudillero_BakeObject024_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.Cudillero_BakeObject025_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.Cudillero_BakeObject026_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.Cudillero_BakeObject027_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.Cudillero_BakeObject028_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.Cudillero_BakeObject029_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.Cudillero_BakeObject030_mtl} />
          <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.Cudillero_BakeObject032_mtl} />
        </group>
      </group>
      <mesh castShadow receiveShadow geometry={nodes.navMesh.geometry} material={nodes.navMesh.material} position={[0, 0.005, 0]} />
      <group position={[0, -1.201, 15]} scale={0.025}>
        <mesh castShadow receiveShadow geometry={nodes.Cudillero_Bake_Final001.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.CombinedMesh.geometry} material={materials.Cudillero_BakeObject031_mtl} />
      <mesh castShadow receiveShadow geometry={nodes.CombinedMesh_1.geometry} material={materials.Cudillero_BakeObject033_mtl} />
    </group>
  )
}

useGLTF.preload('/gltf/hubs.glb')
